asdf = [0, 1, 2, 3, 4, 5, 6]
print(asdf[0])
print(asdf[1])
print(asdf[2])
print(asdf[-3])
print(asdf[-2])
print(asdf[-1])
print("=====")
print("=====")
print("=====")
asdf2 = []
asdf2.append([0, 0])
asdf2.append([1, 1])
asdf2.append([2, 2])
asdf2.append([3, 3])
asdf2.append([4, 4])
asdf2.append([5, 5])
asdf2.append([6, 6])
print(asdf2[0])
print(asdf2[1])
print(asdf2[-2])
print(asdf2[-1])
print("=====")
print("=====")
print("=====")
some_string = ""
some_string += str(asdf2[0])
some_string += str(asdf2[1])
print(some_string)
print("=====")
print("=====")
print("=====")
print(len(asdf2))

asdf3 = [1]
print(len(asdf3))